version: 2.1

jobs:

  debian-build:

    docker:
    - image: s0600204/dpkg-build

    resource_class: small

    working_directory: /mnt/ramdisk

    steps:

    ## Checkout code
    - checkout
    - run:
        name: Switch branch
        command: |
          git checkout debian

    ## Install build dependencies
    - run:
        name: Install build dependencies
        command: |
          apt-get update
          apt-get install `ddepextract`

    ## Build
    - run:
        name: Build package
        command: |
          gbp buildpackage

    ## Upload
    - store_artifacts:
        path: debian/build

workflows:

  create-debian-artifact:
    jobs:
    - debian-build:
        filters:
          branches:
            only:
            - debian
